name = "Absorption"
uuid = "eb14e3ba-90c8-11ed-0ecf-1dd2ea0d109c"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Jutul = "2b460a1a-8a2b-45b2-b125-b5c536396eb9"
JutulDarcy = "82210473-ab04-4dce-b31b-11573c4f8e0a"
JutulViz = "04276eb3-add5-4ac7-8b2a-1bd9f0edb6e2"
MultiComponentFlash = "35e5bd01-9722-4017-9deb-64a5d32478ff"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
